### ISSUE TITLE
Error in 3D obj , especially Neck !

### ISSUE THREAD

**Issue by TharHtetAungg** [JunukCha/MultiPerson#2]
Hello, the ouput mesh file seem to have error, espeically in neck . I already change the neek parameters to neck in Yolo but the mesh shape is not correct. Can you help me to check it ? 
![mesh](https://github.com/JunukCha/MultiPerson/assets/79152768/13b1d472-89cc-4ade-9844-26df5cb20c1e)
![mesh](https://github.com/JunukCha/MultiPerson/assets/79152768/1b94309f-0575-4473-aba5-bc6d8f1d873e)

**Comment by JunukCha** [comment]
I apologize for the late reply.

Can you show me the input image and code?

**Comment by TharHtetAungg** [comment]
Sorry, I cannot share the input image because it is a sensitive body image for privacy. I try to solve that error by changing the target width and height of the image. 

But I have another question, I saw the output has 3 mesh obj, even I used input image with one person. How can I remove the unnecessary obj file? I want only one obj file. And also how can I find the output file path? Is it in the output ultis ?

**Comment by TharHtetAungg** [comment]
Thank you for your reply. Could you tell me where can I edit the code to get one obj file?

**Comment by JunukCha** [comment]
I've already revised the code and updated it on github. https://github.com/JunukCha/MultiPerson/blob/70cc6f49821e4dcfe10820ebaf80c71732b77e76/demo.py#L113-L116 for more information.

**Comment by TharHtetAungg** [comment]
Thank you for your supporting @JunukCha
