### ISSUE TITLE
How to hide post processing result ? 

### ISSUE THREAD

**Issue by MilesTheProwler** [JunukCha/MultiPerson#3]
Hello Sir, 

How can I hide post-processing result? 
![image](https://github.com/JunukCha/MultiPerson/assets/134680400/19bdef67-9c77-45fe-b14c-44dd458cf9fd)

Thanks.

**Comment by JunukCha** [comment]
You can delete or comment out print code in function 
1. "do_detection" L99~102 YOLOv4/tool/torch_utils.py.
        print('-----------------------------------')
        print('           Preprocess : %f' % (t1 - t0))
        print('      Model Inference : %f' % (t2 - t1))
        print('-----------------------------------')
        
2. "post_processing" L313~317 YOLOv4/tool/utils.py.
    print('-----------------------------------')
    print('       max and argmax : %f' % (t2 - t1))
    print('                  nms : %f' % (t3 - t2))
    print('Post processing total : %f' % (t3 - t1))
    print('-----------------------------------')

3. "split_boxes_cv2" L46 lib/utils/img_utils.py
print('%s: %f' % (class_names[cls_id], cls_conf))

**Comment by NaToh5** [comment]
Thank you , Sir!
