### ISSUE TITLE
Suggestion for body texture on your model? 

### ISSUE THREAD

**Issue by MilesTheProwler** [JunukCha/MultiPerson#4]
Hello, can you give me some advice or tips about the skin texture on your repo model ? or Will you provide the texture source code in the future ? 

Thanks.

**Comment by JunukCha** [comment]
Hello. I have no plan to provide source code related to texture.

However, as far as I know, I can give you some tips. Are you wondering how to put skin texture on mesh in the presence of skin texture?

**Comment by MilesTheProwler** [comment]
Yes, I want to apply human skin texture from input image to your mesh model (output).

**Comment by JunukCha** [comment]
Do you mean that you estimate skin texture from input image? (How to estimate skin texture) or Do you already have pre-supplied skin texture? (How to apply skin texture to mesh model)

If it's the latter, could you upload skin texture file?

**Comment by MilesTheProwler** [comment]
My current problem is that I dont have a model that can do the human body texture from human images and try to apply that texture into meshes.

**Comment by JunukCha** [comment]
Then, how about using PIFu(https://shunsukesaito.github.io/PIFu/) pipeline? PIFu can estimate the texture of human. You can use mesh vertices from my mesh estimator as X in Figure 2 of PIFu. However, PIFu doesn't support multi-person.

**Comment by MilesTheProwler** [comment]
PIFu meshes are really bad and not accurate. I already try but I like your model more. Do you have any social account, so that we can chat more from there ?

**Comment by JunukCha** [comment]
My linkedin:
https://www.linkedin.com/in/%EC%A4%80%EC%9A%B1-%EC%B0%A8-365474251/

Please understand that the answer may be slow.
